# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2HZCeyK7nrWqj4RgopLyXUvPzjJgasH
"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
import numpy as np


#Database
# x = Data, y = Target
x = [[2],[4],[6],[8],[10],[12],[14],[16],[18],[20],[22]]
y = [4, 16, 36, 64, 100, 144, 196, 256, 324,400,484]

#Data uji
predict = np.array([[24]])
poly = PolynomialFeatures(degree=2)
x_=poly.fit_transform(x)
predict_ = poly.fit_transform(predict)
regr = linear_model.LinearRegression()
regr.fit(x_,y)

#Menampilkan data prediksi
print("Prediksi")
print("Input = ", predict)
print("Output = ", regr.predict(predict_))