# -*- coding: utf-8 -*-
"""Tugas Regresi Linear Kamis 1/12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VVEjTAdA7sE_UCSxwwzR_hDokcepe8_X
"""

import numpy as np
from sklearn.linear_model import LinearRegression

x = [[1.5],[2.5],[3.5],[4.5],[5.5],[6.5],[7.5],[8.5],[9.5],[10.5]]
y = [3,5,7,9,11,13,15,17,19,21]

regr = LinearRegression ().fit(x,y)
regr.score(x,y)


predict = np.array([[181]])

print ("Prediksi")
print ("Input =", predict)
print ("Output = ",regr.predict(predict))